Style/Documentation:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: no_comma

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/CaseIndentation:
  IndentOneStep: true

Style/SingleLineBlockParams:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/MethodLength:
  Max: 7

Metrics/ParameterLists:
  Max: 4

Metrics/LineLength:
  Exclude:
    - Guardfile

Style/GlobalVars:
  Exclude:
    - Guardfile

Style/RegexpLiteral:
  Exclude:
    - Guardfile
    - perscribo-unicorn.gemspec
